name: coverage
on: push

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup-node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.PRIVATE_SSH }}
      - name: install
        run: npm ci
      - name: test+coverage
        run: npm run coverage
        env:
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      - name: upload artifacts
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: coverage
          path: coverage
